"""Curated seed data: BSOS entity name → IFC property set recommendations.

Each entry maps a bsos entity name to one or more (ifc_class, pset_name,
property_name, value_type, description, rationale) tuples.

Run `bsos seed-psets` to load this into the database.
"""

# Seed data format:
# entity_name -> list of (ifc_class, pset_name, property_name, value_type, description, rationale)
SEED: dict[str, list[tuple[str, str, str, str, str, str]]] = {
    # ── Physical components ────────────────────────────────────────────────────
    "Wall": [
        ("IfcWall", "Pset_WallCommon", "IsExternal", "IfcBoolean",
         "True if the wall forms part of the external envelope",
         "Required for energy and weathertightness compliance checks"),
        ("IfcWall", "Pset_WallCommon", "LoadBearing", "IfcBoolean",
         "True if the wall carries structural loads",
         "Needed for structural analysis and demolition risk assessment"),
        ("IfcWall", "Pset_WallCommon", "FireRating", "IfcLabel",
         "Fire resistance rating, e.g. '60' for 60-minute rating",
         "Required for compartmentation checks"),
        ("IfcWall", "Pset_WallCommon", "AcousticRating", "IfcLabel",
         "Sound reduction index (Rw) or STC rating",
         "Required for acoustic performance verification"),
        ("IfcWall", "Pset_WallCommon", "ThermalTransmittance", "IfcThermalTransmittanceMeasure",
         "U-value in W/(m²·K)",
         "Required for energy performance checks on external walls"),
    ],
    "Door": [
        ("IfcDoor", "Pset_DoorCommon", "IsExternal", "IfcBoolean",
         "True if the door opens to the exterior",
         "Affects weathersealing, thermal, and security requirements"),
        ("IfcDoor", "Pset_DoorCommon", "FireRating", "IfcLabel",
         "Fire resistance rating, e.g. 'FD30' for 30-minute door",
         "Required for fire compartmentation compliance"),
        ("IfcDoor", "Pset_DoorCommon", "AcousticRating", "IfcLabel",
         "Sound reduction index (Rw) of the door assembly",
         "Required for acoustic separation checks"),
        ("IfcDoor", "Pset_DoorCommon", "SecurityRating", "IfcLabel",
         "Security classification, e.g. 'RC2' or 'Class 1'",
         "Relevant for access control and building security assessments"),
        ("IfcDoor", "Pset_DoorCommon", "HandicapAccessible", "IfcBoolean",
         "True if the door meets accessibility requirements (width, hardware)",
         "Required for accessibility compliance checks"),
    ],
    "Window": [
        ("IfcWindow", "Pset_WindowCommon", "IsExternal", "IfcBoolean",
         "True if the window is part of the external envelope",
         "Affects thermal, weathertightness, and acoustic requirements"),
        ("IfcWindow", "Pset_WindowCommon", "FireRating", "IfcLabel",
         "Fire resistance rating of the window assembly",
         "Required for fire compartmentation at openings"),
        ("IfcWindow", "Pset_WindowCommon", "AcousticRating", "IfcLabel",
         "Sound reduction index (Rw) of the glazed assembly",
         "Required for acoustic performance verification"),
        ("IfcWindow", "Pset_WindowCommon", "ThermalTransmittance", "IfcThermalTransmittanceMeasure",
         "U-value in W/(m²·K) of the window assembly",
         "Required for energy performance checks"),
        ("IfcWindow", "Pset_WindowCommon", "GlazingAreaFraction", "IfcNormalisedRatioMeasure",
         "Ratio of glazed area to total window area (0.0–1.0)",
         "Used for solar gain and daylight calculations"),
    ],
    "Staircase": [
        ("IfcStair", "Pset_StairCommon", "FireRating", "IfcLabel",
         "Fire resistance rating of the stair construction",
         "Required for protected escape route compliance"),
        ("IfcStair", "Pset_StairCommon", "IsExternal", "IfcBoolean",
         "True if the stair is in the external environment",
         "Affects slip resistance, handrail, and weathering requirements"),
        ("IfcStair", "Pset_StairCommon", "HandicapAccessible", "IfcBoolean",
         "True if the stair meets accessibility standards",
         "Required for inclusive design compliance"),
    ],
    "Ramp": [
        ("IfcRamp", "Pset_RampCommon", "FireRating", "IfcLabel",
         "Fire resistance rating of the ramp structure",
         "Required for fire compartmentation in protected routes"),
        ("IfcRamp", "Pset_RampCommon", "IsExternal", "IfcBoolean",
         "True if the ramp is in the external environment",
         "Affects surface finish and drainage requirements"),
        ("IfcRamp", "Pset_RampCommon", "HandicapAccessible", "IfcBoolean",
         "True if the ramp gradient meets accessibility standards (≤1:20)",
         "Required for accessibility compliance checks"),
    ],
    "Roof": [
        ("IfcRoof", "Pset_RoofCommon", "LoadBearing", "IfcBoolean",
         "True if the roof structure carries imposed loads",
         "Needed for structural analysis"),
        ("IfcRoof", "Pset_RoofCommon", "FireRating", "IfcLabel",
         "External fire performance rating, e.g. 'BROOF(t4)'",
         "Required for building regulations compliance"),
        ("IfcRoof", "Pset_RoofCommon", "AcousticRating", "IfcLabel",
         "Sound reduction index relevant to roof/ceiling assembly",
         "Required for acoustic performance verification"),
        ("IfcRoof", "Pset_RoofCommon", "ThermalTransmittance", "IfcThermalTransmittanceMeasure",
         "U-value in W/(m²·K)",
         "Required for energy performance checks"),
    ],
    "Slab": [
        ("IfcSlab", "Pset_SlabCommon", "IsExternal", "IfcBoolean",
         "True if the slab is exposed to external conditions (e.g. ground floor)",
         "Affects thermal, damp, and insulation requirements"),
        ("IfcSlab", "Pset_SlabCommon", "LoadBearing", "IfcBoolean",
         "True if the slab carries structural loads",
         "Needed for structural analysis"),
        ("IfcSlab", "Pset_SlabCommon", "FireRating", "IfcLabel",
         "Fire resistance rating (minutes) as a floor/ceiling element",
         "Required for fire compartmentation"),
        ("IfcSlab", "Pset_SlabCommon", "ThermalTransmittance", "IfcThermalTransmittanceMeasure",
         "U-value in W/(m²·K) for ground-bearing or exposed slabs",
         "Required for energy performance checks"),
    ],
    "Column": [
        ("IfcColumn", "Pset_ColumnCommon", "LoadBearing", "IfcBoolean",
         "True if the column is part of the primary structural frame",
         "Always true for structural columns — used in analysis filtering"),
        ("IfcColumn", "Pset_ColumnCommon", "FireRating", "IfcLabel",
         "Fire resistance rating in minutes",
         "Required for structural fire engineering checks"),
        ("IfcColumn", "Pset_ColumnCommon", "IsExternal", "IfcBoolean",
         "True if the column is in the external environment",
         "Affects corrosion protection and weathering requirements"),
    ],
    "Beam": [
        ("IfcBeam", "Pset_BeamCommon", "LoadBearing", "IfcBoolean",
         "True if the beam is part of the primary structural frame",
         "Needed for structural analysis and fire engineering"),
        ("IfcBeam", "Pset_BeamCommon", "FireRating", "IfcLabel",
         "Fire resistance rating in minutes",
         "Required for structural fire engineering checks"),
        ("IfcBeam", "Pset_BeamCommon", "IsExternal", "IfcBoolean",
         "True if the beam is in the external environment",
         "Affects corrosion protection and weathering requirements"),
    ],
    "Foundation": [
        ("IfcFooting", "Pset_FootingCommon", "LoadBearing", "IfcBoolean",
         "True if this element transfers loads to the ground",
         "Always true for foundations — used in analysis"),
    ],
    "Ceiling": [
        ("IfcCovering", "Pset_CoveringCommon", "FireRating", "IfcLabel",
         "Fire resistance contribution to the floor/ceiling assembly",
         "Required for fire compartmentation checks"),
        ("IfcCovering", "Pset_CoveringCommon", "AcousticRating", "IfcLabel",
         "Sound absorption class or impact sound improvement (ΔLw)",
         "Required for acoustic performance verification"),
    ],
    # ── Spaces ─────────────────────────────────────────────────────────────────
    "Office": [
        ("IfcSpace", "Pset_SpaceCommon", "OccupancyType", "IfcLabel",
         "Occupancy classification, e.g. 'Office'",
         "Required for fire strategy, ventilation, and lighting calculations"),
        ("IfcSpace", "Pset_SpaceCommon", "GrossFloorArea", "IfcAreaMeasure",
         "Gross floor area in m² including wall thicknesses",
         "Required for area schedule, cost, and regulatory compliance"),
        ("IfcSpace", "Pset_SpaceCommon", "NetFloorArea", "IfcAreaMeasure",
         "Net usable floor area in m²",
         "Used for occupancy density and furniture layout checks"),
        ("IfcSpace", "Pset_SpaceCommon", "IsExternal", "IfcBoolean",
         "False for internal office spaces",
         "Used to filter external/internal in energy models"),
    ],
    "Entrance Lobby": [
        ("IfcSpace", "Pset_SpaceCommon", "OccupancyType", "IfcLabel",
         "Occupancy classification, e.g. 'Circulation'",
         "Required for fire strategy and ventilation calculations"),
        ("IfcSpace", "Pset_SpaceCommon", "IsExternal", "IfcBoolean",
         "False (internal) or True if lobby is semi-external",
         "Affects thermal and weathertightness treatment in energy models"),
        ("IfcSpace", "Pset_SpaceCommon", "GrossFloorArea", "IfcAreaMeasure",
         "Gross floor area in m²",
         "Required for area schedule and regulatory compliance"),
        ("IfcSpace", "Pset_LightingDesign", "ArtificialLighting", "IfcBoolean",
         "True if artificial lighting is installed",
         "Set to False to flag a requirement for natural light in the lobby"),
        ("IfcSpace", "Pset_LightingDesign", "AmbientIlluminance", "IfcIlluminanceMeasure",
         "Average maintained illuminance in lux",
         "Recommended ≥200 lux for entrance lobbies per CIBSE LG5"),
    ],
    "Bathroom": [
        ("IfcSpace", "Pset_SpaceCommon", "OccupancyType", "IfcLabel",
         "Occupancy classification, e.g. 'Bathroom'",
         "Required for ventilation (extract rate) and acoustic calculations"),
        ("IfcSpace", "Pset_SpaceCommon", "GrossFloorArea", "IfcAreaMeasure",
         "Gross floor area in m²",
         "Required for area schedule"),
    ],
    "Toilet": [
        ("IfcSpace", "Pset_SpaceCommon", "OccupancyType", "IfcLabel",
         "Occupancy classification, e.g. 'WC'",
         "Required for ventilation (extract rate) and sanitary fixture counts"),
        ("IfcSpace", "Pset_SpaceCommon", "GrossFloorArea", "IfcAreaMeasure",
         "Gross floor area in m²",
         "Required for area schedule"),
    ],
    "Kitchen": [
        ("IfcSpace", "Pset_SpaceCommon", "OccupancyType", "IfcLabel",
         "Occupancy classification, e.g. 'Kitchen'",
         "Required for ventilation (extract rate) and acoustic calculations"),
        ("IfcSpace", "Pset_SpaceCommon", "GrossFloorArea", "IfcAreaMeasure",
         "Gross floor area in m²",
         "Required for area schedule and equipment layout checks"),
    ],
    "Bedroom": [
        ("IfcSpace", "Pset_SpaceCommon", "OccupancyType", "IfcLabel",
         "Occupancy classification, e.g. 'Bedroom'",
         "Required for fire strategy, ventilation, and acoustic calculations"),
        ("IfcSpace", "Pset_SpaceCommon", "GrossFloorArea", "IfcAreaMeasure",
         "Gross floor area in m²",
         "Required for habitable room area compliance checks (e.g. ≥7.5 m²)"),
        ("IfcSpace", "Pset_SpaceCommon", "NetFloorArea", "IfcAreaMeasure",
         "Net usable floor area in m²",
         "Used for bedroom occupancy and furniture layout checks"),
    ],
    "Living Room": [
        ("IfcSpace", "Pset_SpaceCommon", "OccupancyType", "IfcLabel",
         "Occupancy classification, e.g. 'Living Area'",
         "Required for fire strategy and ventilation calculations"),
        ("IfcSpace", "Pset_SpaceCommon", "GrossFloorArea", "IfcAreaMeasure",
         "Gross floor area in m²",
         "Required for area schedule and daylight factor checks"),
        ("IfcSpace", "Pset_SpaceCommon", "NetFloorArea", "IfcAreaMeasure",
         "Net usable floor area in m²",
         "Used for occupancy density and furniture layout checks"),
    ],
    "Meeting Room": [
        ("IfcSpace", "Pset_SpaceCommon", "OccupancyType", "IfcLabel",
         "Occupancy classification, e.g. 'Conference Room'",
         "Required for fire strategy and ventilation (occupant density) calculations"),
        ("IfcSpace", "Pset_SpaceCommon", "GrossFloorArea", "IfcAreaMeasure",
         "Gross floor area in m²",
         "Required for area schedule and occupancy capacity calculations"),
        ("IfcSpace", "Pset_SpaceCommon", "NetFloorArea", "IfcAreaMeasure",
         "Net usable floor area in m²",
         "Used to calculate maximum occupancy per building regulations"),
    ],
    "Corridor": [
        ("IfcSpace", "Pset_SpaceCommon", "OccupancyType", "IfcLabel",
         "Occupancy classification, e.g. 'Circulation'",
         "Required for fire strategy (means of escape) calculations"),
        ("IfcSpace", "Pset_SpaceCommon", "GrossFloorArea", "IfcAreaMeasure",
         "Gross floor area in m²",
         "Required for area schedule"),
    ],
    "Stairwell": [
        ("IfcSpace", "Pset_SpaceCommon", "OccupancyType", "IfcLabel",
         "Occupancy classification, e.g. 'Escape Stair'",
         "Required for fire strategy — escape stairs have specific requirements"),
        ("IfcSpace", "Pset_SpaceCommon", "IsExternal", "IfcBoolean",
         "False for internal protected stairwells",
         "Affects smoke control and fire compartmentation requirements"),
    ],
    "Car Park": [
        ("IfcSpace", "Pset_SpaceCommon", "OccupancyType", "IfcLabel",
         "Occupancy classification, e.g. 'Car Parking'",
         "Required for ventilation (CO extraction), fire strategy, and EV charging calculations"),
        ("IfcSpace", "Pset_SpaceCommon", "GrossFloorArea", "IfcAreaMeasure",
         "Gross floor area in m²",
         "Required for parking bay count and area schedule"),
        ("IfcSpace", "Pset_SpaceCommon", "IsExternal", "IfcBoolean",
         "True if open-sided/surface car park; False if enclosed",
         "Affects ventilation strategy and fire engineering approach"),
    ],
    "Reception Area": [
        ("IfcSpace", "Pset_SpaceCommon", "OccupancyType", "IfcLabel",
         "Occupancy classification, e.g. 'Reception'",
         "Required for fire strategy and ventilation calculations"),
        ("IfcSpace", "Pset_SpaceCommon", "GrossFloorArea", "IfcAreaMeasure",
         "Gross floor area in m²",
         "Required for area schedule"),
        ("IfcSpace", "Pset_SpaceCommon", "NetFloorArea", "IfcAreaMeasure",
         "Net usable floor area in m²",
         "Used for desk/counter layout and occupancy checks"),
    ],
}

# Fallback property sets by entity_type, returned when no entity-specific mapping exists.
# Values are list of (ifc_class, pset_name, property_name, value_type, description, rationale).
ENTITY_TYPE_DEFAULTS: dict[str, list[tuple[str, str, str, str, str, str]]] = {
    "space": [
        ("IfcSpace", "Pset_SpaceCommon", "OccupancyType", "IfcLabel",
         "Occupancy classification for this space",
         "Required for fire strategy and mechanical/electrical system design"),
        ("IfcSpace", "Pset_SpaceCommon", "GrossFloorArea", "IfcAreaMeasure",
         "Gross floor area in m²",
         "Required for area schedules and regulatory compliance"),
        ("IfcSpace", "Pset_SpaceCommon", "IsExternal", "IfcBoolean",
         "True if the space is outside the thermal envelope",
         "Affects energy model boundary conditions"),
    ],
    "component": [
        ("IfcBuildingElement", "Pset_ManufacturerTypeInformation", "GlobalTradeItemNumber", "IfcIdentifier",
         "GTIN or product code for the manufactured element",
         "Useful for procurement and embodied carbon tracking"),
    ],
    "system": [
        ("IfcSystem", "Pset_SystemFurnitureElementTypeWorkSurface", "NominalLength", "IfcPositiveLengthMeasure",
         "Nominal length of the system element",
         "Used for quantity take-off"),
    ],
}
