"""phase2_tables

Revision ID: 5b0f3e266c92
Revises: 8661e7e10d0b
Create Date: 2026-05-22 20:00:49.331246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5b0f3e266c92'
down_revision: Union[str, None] = '8661e7e10d0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('antipatterns',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('consequences', sa.Text(), nullable=True),
    sa.Column('mitigations', sa.Text(), nullable=True),
    sa.Column('source_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('extraction_run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('knowledge_origin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rationale', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('conflict_evaluated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_antipatterns_name'), 'antipatterns', ['name'], unique=False)
    op.create_table('constraints',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rule', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('constraint_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('exceptions', sa.Text(), nullable=True),
    sa.Column('source_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('extraction_run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('knowledge_origin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rationale', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('conflict_evaluated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_constraints_subject_id'), 'constraints', ['subject_id'], unique=False)
    op.create_table('forces',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('direction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('affects', sa.Text(), nullable=True),
    sa.Column('source_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('extraction_run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('knowledge_origin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rationale', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('conflict_evaluated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forces_name'), 'forces', ['name'], unique=False)
    op.create_table('patterns',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('problem', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('force_descriptions', sa.Text(), nullable=True),
    sa.Column('force_ids', sa.Text(), nullable=True),
    sa.Column('solution', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('consequences', sa.Text(), nullable=True),
    sa.Column('related_pattern_names', sa.Text(), nullable=True),
    sa.Column('related_pattern_ids', sa.Text(), nullable=True),
    sa.Column('emergent_properties', sa.Text(), nullable=True),
    sa.Column('source_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('extraction_run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('knowledge_origin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rationale', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('conflict_evaluated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patterns_name'), 'patterns', ['name'], unique=False)
    op.create_table('pending_entity_refs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_force_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pending_force_refs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('failure_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pattern_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('force_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pending_pattern_refs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_pattern_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pending_predicates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vocabulary_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('flagged_for_review', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_predicates_value'), 'pending_predicates', ['value'], unique=True)
    op.create_table('pending_spatial_relation_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vocabulary_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('flagged_for_review', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_spatial_relation_types_value'), 'pending_spatial_relation_types', ['value'], unique=True)
    op.create_table('predicate_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_predicate', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('to_predicate', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predicate_mappings_from_predicate'), 'predicate_mappings', ['from_predicate'], unique=False)
    op.create_table('process_relations',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('predecessor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('successor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hard_constraint', sa.Boolean(), nullable=False),
    sa.Column('source_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('extraction_run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('knowledge_origin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rationale', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conflict_evaluated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('predecessor_id', 'successor_id', 'source_model')
    )
    op.create_index(op.f('ix_process_relations_predecessor_id'), 'process_relations', ['predecessor_id'], unique=False)
    op.create_index(op.f('ix_process_relations_successor_id'), 'process_relations', ['successor_id'], unique=False)
    op.create_table('spatial_relations',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('relation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('object_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('extraction_run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('knowledge_origin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rationale', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('conflict_evaluated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spatial_relations_object_id'), 'spatial_relations', ['object_id'], unique=False)
    op.create_index(op.f('ix_spatial_relations_subject_id'), 'spatial_relations', ['subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spatial_relations_subject_id'), table_name='spatial_relations')
    op.drop_index(op.f('ix_spatial_relations_object_id'), table_name='spatial_relations')
    op.drop_table('spatial_relations')
    op.drop_index(op.f('ix_process_relations_successor_id'), table_name='process_relations')
    op.drop_index(op.f('ix_process_relations_predecessor_id'), table_name='process_relations')
    op.drop_table('process_relations')
    op.drop_index(op.f('ix_predicate_mappings_from_predicate'), table_name='predicate_mappings')
    op.drop_table('predicate_mappings')
    op.drop_index(op.f('ix_pending_spatial_relation_types_value'), table_name='pending_spatial_relation_types')
    op.drop_table('pending_spatial_relation_types')
    op.drop_index(op.f('ix_pending_predicates_value'), table_name='pending_predicates')
    op.drop_table('pending_predicates')
    op.drop_table('pending_pattern_refs')
    op.drop_table('pending_force_refs')
    op.drop_table('pending_entity_refs')
    op.drop_index(op.f('ix_patterns_name'), table_name='patterns')
    op.drop_table('patterns')
    op.drop_index(op.f('ix_forces_name'), table_name='forces')
    op.drop_table('forces')
    op.drop_index(op.f('ix_constraints_subject_id'), table_name='constraints')
    op.drop_table('constraints')
    op.drop_index(op.f('ix_antipatterns_name'), table_name='antipatterns')
    op.drop_table('antipatterns')
    # ### end Alembic commands ###
